# Generated by Django 4.1.13 on 2023-11-23 06:21

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChordImages',
            fields=[
                ('chord_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('images', djongo.models.fields.ArrayField(model_container=core.models.ImgLink)),
            ],
        ),
    ]
